development:
  access_key_id: AKIAIIZHEAEZ3HLRAW5A
  secret_access_key: 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
test:
  access_key_id: AKIAIIZHEAEZ3HLRAW5A
  secret_access_key: CHTOniYi3CWSxWnx/Okcswd/MW9VGbwb/VTzL3wn
production:
  access_key_id: YOUR_ACCESS_KEY_ID
  secret_access_key: YOUR_SECRET_ACCESS_KEY
